name: Get Latest Stream Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16.x

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Use pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Check if stream changed
        id: stream-changed
        run: pnpm exec node-ts ./scripts/check-if-stream-changed.ts

      - name: Deploy to GitHub Pages 🚀
        if: steps.stream-changed.outputs.stream-changed == 'true'
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: dist
