name: Sychronize site with latest stream

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  check-stream-updated:
    name: Check if stream updated
    runs-on: ubuntu-latest
    outputs:
      up-to-date: ${{ steps.stream-changed.up-to-date }}
    steps:
      - name: Check if stream changed
        id: stream-changed
        run: |
          current_livestream_video_id=$(curl -s https://gapyearstream.com/current-livestream-video-id)
          newest_livestream_video_id=$(curl -s https://www.youtube.com/channel/UCevgC7xkuvSWEvA9tLV9XBg/live | sed -n 's/.*<link rel="canonical" href="\([^"]*\)">.*/\1/p' | sed -n 's/.*watch\?v=\(.*\)/\1/p')

          if [ $current_livestream_video_id = $newest_livestream_video_id ];
          then
            echo "::set-output name=UP_TO_DATE::1"
          else
            echo "::set-output name=UP_TO_DATE::0"
          fi

  update-site:
    name: Updates the site if stream updated
    runs-on: ubuntu-latest
    needs: check-stream-updated
    if: needs.check-stream-updated.outputs.up-to-date == '0'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16.x

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Use pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Install dependencies and build frontend
        run: pnpm install && pnpm build

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: dist
